create table CUSTOMERS
(
    CUSTOMER_ID   NUMBER(9),
    CUSTOMER_CODE VARCHAR2(5),
    COMPANY_NAME  VARCHAR2(40),
    CONTACT_NAME  VARCHAR2(30),
    CONTACT_TITLE VARCHAR2(30),
    ADDRESS       VARCHAR2(60),
    CITY          VARCHAR2(15),
    REGION        VARCHAR2(15),
    POSTAL_CODE   VARCHAR2(10),
    COUNTRY       VARCHAR2(15),
    PHONE         VARCHAR2(24),
    FAX           VARCHAR2(24)
)
/

