create table ORDERS
(
    ORDER_ID         NUMBER(9),
    CUSTOMER_ID      NUMBER(9),
    EMPLOYEE_ID      NUMBER(9),
    ORDER_DATE       DATE,
    REQUIRED_DATE    DATE,
    SHIPPED_DATE     DATE,
    SHIP_VIA         NUMBER(9),
    FREIGHT          NUMBER(10, 2) default 0,
    SHIP_NAME        VARCHAR2(40),
    SHIP_ADDRESS     VARCHAR2(60),
    SHIP_CITY        VARCHAR2(15),
    SHIP_REGION      VARCHAR2(15),
    SHIP_POSTAL_CODE VARCHAR2(10),
    SHIP_COUNTRY     VARCHAR2(15)
)
/

